var lang_en_US = /** @class */ (function () {
    function lang_en_US() {
    }
    lang_en_US.langName = "en-US";
    lang_en_US.langDesc = "English";
    lang_en_US.items = {
        "K线指标设置": "K-line Indicator Setting",
        "WR指标设置提示": "WR is a concussion index, which measures whether it is overbought or oversold according to the price swing point. It measures the ratio of the distance between the peak value (the highest price) and the closing price per day and the range of price fluctuations over a certain period of time (such as 7 days, 14 days, 28 days, etc.) in order to provide a signal of price trend reversal.",
        "RSI指标设置提示": "RSI is a technical analysis tool for comparing price movements to express price intensity, among which RSI of 14 days is the most representative.",
        "KDJ指标设置提示": "KDJ calculates the premature random value of the last calculation cycle through the ratio of the closing price of the highest price, the lowest price and the last calculation cycle in a specific period (usually 9, 9 weeks, etc.), and then calculates the K value, the D value and the J value according to the method of smoothing moving average. And draw a graph to judge the price trend.",
        "MACD指标设置提示": "MACD consists of a set of curves and graphs, which are calculated by the difference between the exponential moving average (EMA) of fast and slow price or index changes at closing time. \"S\" refers to the shorter period of EMA, while \"L\" refers to the longer period of EMA, the most commonly used is the 12 and 26 days of EMA.",
        "保存": "Save",
        "成功保存": "Saved successfully",
        "BOLL指标设置提示": "BOLL is also called Brin belt. Its basic form is a banded channel composed of three track lines (one for the middle track and one for the upper and lower track). The middle rail is the average cost of the price, and the upper rail and the lower rail can be regarded as the pressure line and the support line of the price respectively.",
        "重置": "Reset",
        "MA指标设置提示": "The MA index is connected by the sum of closing prices over a period of time and calculates the average number, which can smooth short-term fluctuations and reflect long-term trends or cycles.",
        "指标设置": "Indicator Setting",
        "请输入登录密码": "Please enter password",
        "安全验证": "Security Verification",
        "交易次数": "Trading times",
        "{0}次": "{0} time{1}",
        "赔付金额": "Amount of compensation",
        "亏损金额": "Loss Amount",
        "主图": "Main graph",
        "副图": "Sub graph",
        "指标": "Indicator",
        "同意": "Agree",
        "跟单亏损赔偿": "Compensation of Following",
        "自动跟单": "Automatic Following order",
        "跟单": "Following order",
        "跟单-简": "F",
        "手动下单": "Manually order",
        "(苹果支持面部验证)": "(iOS support FaceID)",
        "指纹多次验证失败，app将退出": "Multiple fingerprint verification failures，app will quit.",
        "输入密码": "Enter password",
        "生物识别": "Bio-identify",
        "指纹验证": "Fingerprint verification",
        "指纹验证失败": "Fingerprint verification failed",
        "您的设备不支持指纹识别功能,或者您还没有在您的手机里录入指纹": "Your device does not support fingerprint recognition, or you have not entered fingerprints in your mobile phone yet.",
        "修改": "Modify",
        "未设置": "Not set",
        "支付密码": "Payment Password",
        "登录密码": "Login Password",
        "指纹密码": "Fingerprint Verification",
        "去认证": "Verify",
        "高级认证": "Advanced Certification",
        "中": "Medium",
        "安全等级": "Safety Level",
        "首页": "Home",
        "行情": "Quotation",
        "交易": "Trade",
        "我的": "Account",
        "未登录": "Not logged in",
        "高手排行榜": "Top Ranking",
        "活动专区": "Activity Area",
        "我的推广": "My Promotion",
        "新手教学": "Beginner's Guide",
        "热门品种推荐": "Recommendation of Popular Varieties",
        "用户": "User",
        "排行": "Ranking",
        "收益率": "Winning(%)",
        "盈利金额": "Profit",
        "品种": "Instruments",
        "最新价": "Price",
        "涨跌幅": "Change (%)",
        "行情列表-涨": "#0ea41a",
        "行情列表-跌": "#f5221a",
        "交易中": "Trading",
        "未开盘": "Closed",
        "停止交易": "Closed",
        "最高": "High",
        "最低": "Low",
        "今开": "Open",
        "昨收": "Close",
        "分时": "Line",
        "n分钟": "{0}min{1}",
        "n小时": "{0}hour{1}",
        "日K": "D-K",
        "更多": "more",
        "买入做多": "Buy",
        "卖出做空": "Sell",
        "7x24小时": "7x24 Hours",
        "交易时间": "Trading Time",
        "时间": "Time",
        "开": "Open",
        "高": "High",
        "低": "Low",
        "收": "Close",
        "涨跌额": "Change",
        "成交量": "Volume", "市价": "Market Price", "现价": "Current price", "交易数量": "Trade Volume", "n手": "{0}lot{1}",
        "自定义": "Custom", "融资额": "Leverage Amount",
        "超级链接颜色": "#ef2b2b", "保证金": "Margin", "余额": "Balance", "充值": "Deposit", "设置止盈/止损": "Set stop profit/loss",
        "止盈价格": "Stop Profit Target", "止损价格": "Stop Loss", "手续费率": "Fee(%)", "确定看涨做多": "Confirm Buy",
        "确定看跌做空": "Confirm Sell", "价格": "Price", "点击设置": "click to set", "限价": "Fixed price",
        "隔夜费说明": "Platform will charge the overnight rate to all opening positions after 23:59:59,Overnight Charging Rules:Overnight Charge = Lending Amount ×0.1%",
        "理财风险揭示": "Revealing Financial Risks", "市值": "Market price", "成本价": "Cost price", "用户消息": "User Message",
        "活动消息": "Activity Message", "系统消息": "System Message", "消息提醒": "Messages", "联系客服": "Contact Us", "已掌握清楚，去充值": "Have mastered clearly,go to deposit!",
        "已掌握清楚，去提现": "Mastered clearly, Go cash out!", "已掌握清楚，去下单": "Mastered clearly, go order!", "是": "Yes", "否": "No", "下单": "Order",
        "查看持仓": "Check Positions", "涨": "up", "跌": "down", "出入金相关": "Deposit/Withdrawal", "USDT相关": "USDT", "邀请好友相关": "Invite friends", "交易相关": "Trading Related",
        "利息相关": "Interest", "提现记录": "Details", "资金记录": "Details", "实名认证正在审核": "Real name identification verification is in process",
        "转入金额必须为x的整数倍": "Tip: Transfer amount must be an integer multiple of {0}", "请输入6位验证码": "Please enter a 6-bit verification code",
        "没有读写存储卡相册的权限": "No read-write access to memory cards", "当前价": "Current Price",
        "年化收益广告语": "Available balance annual gain 15%, margin annual gain 25%, deposit now, earn now", "至": "To", "无转入记录": "No transfer history",
        "挂单价": "Order Price", "年化累计收益说明": "Annual gain is accumulated, the gain will be deposited to your account at the beginning of each month.",
        "计息规则说明_title": "Bitcoinwin Interest rules",
        "计息规则说明": "\n                    The gain of yesterday include the available balance multiple the daily interest plus the margin multiple the daily interest.\n\n                    1. Bitcoinwin use compound interest rate,we add your daily gain to the avaiable balance to ensure your gain increasing everyday.\n                    Daily gain = The available balance×0.000383（Annual interest rate 15%）+The margin×0.000613（Annual interest rate 25%）\n                    Example: If your available balance is 10000 USDT and the margin is 1000 USDT\n                    Daily gain : 10000×0.000383+10000×0.000613=3.83+6.13=9.96 USDT\n                    Monthly gain : 10000×(1.000383)^25 + 10000×(1.000613)^25-20000=300.1 USDT\n\n                    2. Your monthly gain will be deposted to your account at the last day of the month(tips: No gain at the withdraw day)\n                    3.Your monthly gain will be deposted to your account at the last day of the month\n                    4.No gain at the withdraw day\n\n                    Very appreciate your support to Bitcoinwin, welcome to invest!\n                    If you have any question, please feel free to contact us at service@bitcoinwin.io\n                ",
        "昨日收益": "Earnings of yesterday",
        "年化累计收益": "Accumulated earnings", "年化累计收益_短": "Annual",
        "认证中...": "Certification auditing...", "审核中...": "Certification auditing...",
        "认证失败": "Certification fail", "等待运营人员审核_审核结果将在一个工作日内返回": "Waiting apporval, the result will be available within one business day",
        "总资金已经不足全部开仓保证金": "Dear clients, your available balance is less than {0}% of the margin, please take care it asap. Thanks.",
        "可用余额收益": "Balance profit", "保证金收益": "Margin profit", "转入金额": "Transfer amount", "成功转入": "Trasfer sucessfully", "转入账户": "Transfer to account",
        "转入记录": "Transfer history", "金额不足": "not enough balance", "请输入转入金额": "Enter the amount to be transferred", "可转入金额": "Transferable amount", "级别": "Level",
        "我的好友列表": "My friends", "好友数量": "Number of friends", "我邀请的好友": "Friends I invited", "好友邀请的好友": "Friends Invited by Friends",
        "我的理财收入": "My investing income", "我的分享收入": "My Shared Income", "收益明细": "Income Details", "分享好友收获": "Share to friends", "好友分享获赠": "From friends",
        "收益明细_可用余额收益": "Profit from balance", "收益明细_保证金收益": "Profit from margin", "本月": "This month", "每日利息": "Day Interest", "月总利息": "Month Interest", "日期": "Date",
        "请选择收款账户": "Please select bank account", "交易Dialog.委托确认": "Order Confirm", "交易Dialog.名称": "Symbol", "交易Dialog.委托价格": "Order position",
        "交易Dialog.委托数量": "Order lots", "交易Dialog.交易数量": "Order lots", "交易Dialog.委托类型": "Order type", "交易方式": "Transaction mode", "买入开仓": "Buying open positions",
        "委托单号": "Order transaction", "交易单号": "Trading transaction", "持仓单号": "ID", "提交成功": "Submit Successfully", "您的委托单已提交": "Your order has been submitted successfully.",
        "立刻体验": "Try it", "充值金额必须等值于": "The deposit amount should not be less than {0} {1} in value", "隔夜利息": "Overnight interest", "产品": "Commodity", "合约号": "Contract Id",
        "撤销的订单": "Cancelled Orders", "网络异常，请稍后再试": "Network error, please try again later", "拷贝地址": "Copy Address", "自动登录": "Automatic sign in", "成功复制": "Copy Completed",
        "请输入止盈": "Please enter stop profit", "请输入止损": "Please enter stop loss", "止损": "Stop Loss", "止盈": "Stop Profit", "委托时间": "Order time", "隔夜息": "Overnight Rate",
        "成功保存到相册": "Saved to album successfully", "推广员升级规则": "Share to friends to win",
        "推广员升级规则_内容": "1.Share benefits to friends\n                    User share the QR code to friend, you will get {0} annually interest of your friend’s available balance\n\n                    2.Share benefits to friends\n                    You can get extra {1} annually interest of your friend’s invitations’ available balance.\n\n                    What are you waiting for? Share it now.\n                ",
        "推广员升级规则_内容_VIP": "Welcome becoming our VIP client. You can enjoy the following benefits from now on:\n\n\n      You can obtain the benefits from your friends\n\n      1. By sharing the QR code to your friends, you will be rewarded with 10USDT if they register and deposit.\n\n      2. You can get {0} annual income from the total funds of the Friends'Account, which is calculated daily and paid monthly.\n\n      3. You can get {2} commission rebate from the transaction fee.\n\n\n\n      Second Level Friend Sharing Benefits\n\n      After your friends share their QR code and invites your friends to join our platform, they can get all the above benefits, and you will get extra:\n\n      1. The annual {1} income of the total funds in the Friends'Account is calculated on a daily basis and paid monthly basis.\n\n      2. You can get {3} commission rebate from your friends transaction fee",
        "点击保存二维码": "Press to save", "发送给好友扫一扫立即赚收益": "Send to frends,earn money immediately", "累计收入": "Grand total amount", "我的好友": "My friends", "收获金额": "Amount received", "邀请好友": "Invite Friends", "设置止盈止损": "Set stop profit/stop loss",
        "入金货币": "Currency Type", "用户操作_detail": "User stop", "系统操作_detail": "Auto stop", "止盈平仓_detail": "Stop profit", "止损平仓_detail": "Stop loss",
        "到达平仓时间_detail": "Arrival time", "规则组平仓_detail": "Auto stop", "系统强平_detail": "Auto stop", "确定要撤销这个委托单吗": "Are you sure want to cancel the order?",
        "确定要撤销所有委托单吗": "Are you sure you want to cancel all orders?", "确定平仓吗": "Confirm to close out position?",
        "止盈价格必须大于": "Stop profit amount  must be greater than {0}", "止损价格必须小于": "Stop loss amount  must be less than {0}", "确定要关闭所有持仓吗": "Are you sure you want to close all positions?",
        "请输入价格": "Enter the price", "价格必须大于": "The price must be greater than {0}", "撤销": "Cancelled", "浮动盈亏": "Current P/L", "完成": "Completed", "交易记录": "Trading Details", "无": "not set",
        "价格_委托": "Price", "数量_委托": "Lot", "实际成交_委托": "Real deals", "一键撤单": "Cancel all orders", "撤单": "Cancel the order", "持仓": "Positions", "持仓中": "Holding position", "账户": "Account",
        "品种名称": "Instruments", "交易列表按钮涨": "#0ea41a,#0ea41a", "交易列表按钮跌": "#f5221a,#f5221a", "TextColor涨": "#0ea41a", "TextColor跌": "#EA3131", "K线Tip涨": "#47f03f",
        "K线Tip跌": "#fd8366", "KLineUpColor": "#1cbc79", "KLineDownColor": "#f34a4c", "买入数量Format": "{0} Lot",
        "买入数量复数Format": "{0} Lots", "Text001": "Automatic closing at {0}, {4} {1} point(s) to earn {2} USD ({3} USDT)", "Text002": "Exchange Rate: {0} USD={1} USDT",
        "触发止损价格": "Stop Loss", "触发止盈价格": "Take Profit", "占用保证金": "Margin", "合计": "Total", "交易费用": "Fee", "可用资金": "Available funds",
        "开仓价": "Open Price", "确定": "OK", "取消": "Cancel", "结算": "Statement", "浮动总盈亏": "Floating PnL", "一键平仓": "Close all positions",
        "冻结保证金": "Margin on hold", "可用余额": "Balance", "仓位": "Trade", "盈亏": "PnL", "单号": "Order No.", "触发止盈": "Take Profit", "触发止损": "Stop Loss",
        "开仓": "Open", "最新平仓": "Last Price", "开仓时间": "Open Time", "平仓时间": "Close Time", "自动平仓": "Automatic closing at {0}", "止盈止损": "Take profit and stop loss",
        "快速平仓": "Close position", "开仓盈利": "Start Trading", "做多": "Buy", "做空": "Sell", "再来一单": "Trade Again", "盈亏n点": "PnL {0} pip(s)", "点n盈利": "pip(s) ({0}) profit",
        "止盈设置范围": "Take profit between 1-240 pip(s)，Stop loss between 1-120 pip(s)", "新手帮助": "Beginners Guide", "钱包": "Wallet", "账户余额": "Balance", "提现": "Withdrawal",
        "提现_法币": "Fiat Money", "提现_USDT": "USDT", "资金明细": "Transaction Details", "交易明细": "Transaction Details", "资金明细_充值": "Deposits", "资金明细_提现": "Withdrawal Details",
        "资金明细_开仓": "Opened", "资金明细_平仓": "Closed", "资金明细_费用": "Fee", "资金明细_余额利息": "Balance interest", "资金明细_保证金利息": "Margin interest", "个人中心": "Account Center",
        "银行卡绑定": "Bind Bank Card", "手机号": "Mobile number", "未认证": "Not certified", "常见问题": "FAQ", "模拟交易": "Demo Trading", "我的徒弟": "My Followers", "挖矿": "Mining",
        "我的收益": "My Income", "关于我们": "About Us", "设置": "Settings", "用户注册": "Sign Up", "手机号登录": "Mobile Sign In", "登陆": "Sign In", "还没有账号去注册": "Sign up now",
        "忘记密码": "Forgot Password?", "请输入密码": "Please enter password", "请输入手机号": "Please enter cellphone number", "获取验证码": "Get Verification Code", "手机找回密码": "Recover password via mobile phone",
        "请输入验证码": "Verification code", "请输入手机验证码": "Verification code", "下一步": "Next", "请输入新密码": "Please enter a new password", "请再次输入新密码": "Password confirm",
        "请输入m密码": "Password(8-16 digits and letters)", "请再次输入密码": "Please enter your password again", "提交": "Submit", "我阅读并同意": "I have read and agree with", "注册协议": "\"User Agreement\"",
        "风险揭示_我的": "Risk Disclosure", "风险揭示": "\"Risk Disclosure\"", "实名认证": "Verified Real Name", "国家": "Country", "请选择国家": "Please choose a country", "姓名": "Full Name",
        "证件号码": "ID Number", "提示输入身份证": "Please enter your ID number and be sure to fill it correct", "提示输入护照": "Please enter your passport number and be sure to fill it correct",
        "提示输入姓名": "Please enter your full name", "币币入金": "Crypto Account", "币币入金提示": "USDT deposits", "法币入金": "Fiat Account", "法币入金提示": "Pay local currency to buy USDT",
        "充值数量": "Deposit Amount", "充值数量提示": "Please enter deposit amount", "USDT充值数量提示": "Minumum deposit is {0}", "立刻充值": "Deposit", "流水号": "OrderId", "状态": "Status",
        "复制": "Copy",
        "我已付款": "I have paid",
        "USDT完成提示": "Note: After completing deposit, please enter the last 6 digits of the order TXID number below.",
        "输入TXID号": "Enter last 6 figures of TXID number", "持卡人姓名": "Full Name", "持卡人姓名提示": "Please enter your full name",
        "银行名称": "Bank Name", "银行名称提示": "Please choose the bank", "开户地址": "Bank Address", "省提示": "Select province", "市提示": "Select city",
        "选择省份": "Select province", "选择城市": "Select city", "绑定银行卡": "Bind Bank Card", "银行卡号": "Bank Card Number",
        "银行卡号提示": "Please enter your bank card number", "银行卡信息核对提示": "Please check your account information carefully and submit if everything correct",
        "法币提现": "Fiat money withdrawal", "USDT提现": "Crypto money withdrawal", "仅支持人民币提现操作": "Only RMB withdrawal operation is supported",
        "仅支持USDT提现操作": "Only USDT withdrawal operation is supported", "提币": "Withdraw in {0}", "可用": "Available Balance", "提币地址": "USDT Wallet Address",
        "提币地址提示": "Enter or paste the address via the copy button", "最小提币数量": "Minumum withdrawal amount is {0}",
        "USDT提币长提示": "For the security purposes, your account security policy has been changed.Use new address for deposit crypto, we will manually check the coins, please be patient.",
        "CNY提币长提示": "In order to protect the security of the fund account, when your account security policy is changed, the password is modified, and the new address is used to withdraw the currency, you must verify that the coin address is correct. Once you turn the error, you will not be able to return.",
        "到账数量": "Received Amount", "立即提现": "Withdraw Now", "提币数量": "Withdrawal Amount", "全部": "All", "手续费": "Fee",
        "设置支付密码": "Setup Payment Password", "请输入n位数的支付密码": "Please enter a payment password of {0} digits",
        "支付密码确认不一致": "Payment password doesn't match",
        "取消设置安装未知来源App": "You have cancelled the installation of the unknown source application, the app upgrade is cancelled! If you want to keep an automatic upgrade of app, please allow the installation of the unknown source application in your phone!",
        "提示用户允许安装未知来源应用程序": "If you want to enter the automatic upgrade program, please allow install an unknown source application.",
        "拒绝读写存储空间": "Please open the software to read and write the memory of mobile phone and access photos, media content and files, and set the permissions to allow APP to obtain the phone number, IMEI, IMSI, otherwise APP will not be able to automatically upgrade and receive notifications!",
        "UPush安装新版本提示": "The new version is available, update in now?", "立刻安装": "Install", "下次安装": "Next Time", "用户名或者密码错误": "Username or password is incorrect",
        "n秒重新获取": "{0}s", "请阅读并同意注册协议": "Please read and agree to the registration agreement.", "密码确认不一致": "Invalid password confirmation",
        "注册成功": "Register Successed", "成功设置密码": "Setup Password Successed", "交易成功": "Trade Successful", "提示数据还在加载": "Loading，Please wait...",
        "自动平仓时间n": "Automatic closing at {0}", "加载更多": "Click to load More", "正在加载": "Loading", "目前还没有数据": "No data to display",
        "没有更多数据了": "No more data to display", "找不到此产品数据": "The product data was not found.", "成功提交": "Submit Successed", "平仓": "Close",
        "模拟行情": "Price", "模拟持仓": "Trades", "成功提交充值信息": "Submit Successed! The deposit result is under examination and approval. It will take about 10-60 minutes. Please wait patiently.",
        "充值金额": "Deposit Amount", "提现金额": "Withdrawal Amount", "提示实名认证": "Please go to the account center for real name authentication first.", "语言选择": "Choose Language",
        "版本": "Version", "退出登录": "Sign Out", "确定退出登陆吗": "Are you sure you want to sign out?", "检查更新": "Check For Updates", "已经是最新版本": "Up to date",
        "成功设置支付密码": "Successfully set payment password", "发现新版本": "New Version is avaiable", "发现新版稍后自动安装": "New version is avaiable，automatic installation later.",
        "收款账户": "Account", "请填写开户地址": "Please fill in the account address.", "成功提交申请等候审批": "Submit your application successfully, please wait for approval.",
        "请输入支付密码": "Please enter the payment password", "请再次输入支付密码": "Please enter the payment password again", "平仓价": "Close Price", "确定n手交易": "Are you sure you want to {0} {1} of {2}?",
        "账户总资产": "Running Balance", "持仓总额": "Trade Amount", "继续下单": "Trade Again", "认证成功": "Authentication succeeds", "重设支付密码": "Reset the payment password",
        "玩法规则": "{0} Trading Rules", "什么是止损": "What is the stop loss?", "什么是止损_内容": "When a single transaction loss amount triggers (equal to) the specified stop loss amount, the trade will be closed by the stop loss automatically. For example, if the XRP \"Buy\" long or \"Sell\" short, the position's loss is -20 the trade will be closed automatically by Stop loss.",
        "什么是止盈": "What is take profit?",
        "什么是止盈_内容": "\"Take profit\" is an amount of money you intend to make in a trade. In your order, you specify an amount in USDT at which trade will close automatically. For example, if open \"Buy\" position in XRP with take profit at 17, it means that the trade will be closed automatically once profit will reach 17 USDT.",
        "成功": "successed", "失败": "failed", "审核中": "operating", "未支付": "waiting for pay", "币种": "Currency", "充值时间": "Deposit Time",
        "金额": "Amount", "正在下载新版本": "Downloading new app", "请先绑定银行卡": "Please bind bank card first", "行情_未开盘": "Close", "行情_停止交易": "Close",
        "行情_交易中": "Open", "打款中": "Paying", "持仓_保证金": "Margin", "持仓_持仓数量": "Holding lots", "登陆失效_请重新登陆": "Login is invalid, please log in again",
        "目前不能进行模拟交易": "The demo trading is expired", "模拟交易操作时间还剩n天": "There are {0} days left for Demo Trading", "网络异常": "network error",
        "持仓盈亏": "Total P/L", "可用保证金": "Available Margin", "平仓线": "Closing out position", "持仓保证金": "Position Margin", "委托": "Pending Order",
        "持仓均价": "Average position", "融资金额": "Leverage Amount", "行情_按钮": "Price", "最大只能n手": "Max. {0} Lots", "点击重新加载": "Click to reload",
        "成功截屏": "Screen shot successfully", "邀请好友得返利": "Invite friends to get bonus", "低门槛 高杠杆 更高收益": "Low requirement, high leverage, higher yield",
        "分享福利说明": "Sharing benefits description", "法币充值": "Fiat Currency deposit", "币币充值": "Cryptocurrency deposit", "支付渠道": "Pay Channel", "马上充值": "Deposit now",
        "充值注意事项": "Precautions:\n1. Minimum deposit amount 50USDT\u2248{0}CNY;\n2. The effective time of each order is 20 minutes, please complete the payment within 20 minutes;\n3. After the payment is completed, if the order status is changed to completed, please contact customer service for processing;\n4. After canceling the OTC deposit order for 5 times on the same day, you cannot continue to deposit. Please cancel the order carefully.",
        "保存到相册": "Save to album", "请输入充值金额": "Please enter the amount of deposit", "已认证": "Verified",
        "分享收益": "Sharing revenue", "已实名": "Real name verified", "个人资料": "personal information", "手机号码": "cellphone number",
        "密码修改": "change Password", "资产": "assets", "请上传护照正反面": "Please upload the front and back of the passport",
        "拍摄正面": "Shooting the front", "拍摄反面": "Shooting the opposite side", "拍摄提示": "Shooting tips",
        "拍摄提示_内容": "1. Please put the documents flat when shooting, and shoot the phone horizontally;\n2. Ensure that the passport frame is complete and the text is clearly visible;\n3. After the photo is uploaded, if you are not satisfied, you can click the photo to shoot again.",
        "分享给朋友": "Share with friends", "交易资产": "Trading assets", "明细": "Detail", "立即还款": "Immediate repayment", "自有资产": "Own assets", "借款": "loan",
        "信用资本": "Credit account", "数字币信用卡": "Cryptocurrency credit card", "余额宝": "YuEBao", "转入余额": "Transfer balance", "累计收益": "Cumulative income",
        "待结算": "Pending settlement", "昨日总收益": "Last day revenue", "余额收益": "Balance income", "账户利息收益": "Account interest income", "年化": "{0}% annualized",
        "邀请收益": "Invitation revenue", "邀请好友收益": "Invite friends to earn", "n人": "{0} people{1}",
        "存钱赚利息广告语": "Deposit money to earn interest?\nThe platform provides the world's lowest 15% + annualized income, high storage, high returns!",
        "首次入金奖励": "First deposit bonus", "信用资本理财资产": "Credit account wealth management assets", "充值信用资本": "Deposit credit assets",
        "提现信用资本": "Withdrawal of credit assets", "历史记录": "historical record", "可用信用金": "Available credit", "还款": "Repayment",
        "提高信用额度": "Increase credit value", "没钱也能做交易": "Can trade without money", "马上提高信用额度": "Immediately increase the credit value",
        "点击设置价格": "Click to set the price", "手续费返佣": "Transaction fee rebate", "确认转入": "Confirm transfer", "筛选": "filter",
        "币币提现": "Currency withdrawal", "法币入金出金流程快捷安全": "Fiat currency deposit and withdrawal process is fast and safe",
        "推荐好友可获丰厚返利": "Recommend friends to get <span style='font-size:0.75rem;font-weight:bold;color:#EA3131;'>rich</span> rebates",
        "交易保证金年化收益n": "Trading Margin Annualized Income <span style='font-size:0.9rem;font-weight:bold;color:#EA3131;'>{0}</span>",
        "低至10USDT一手": "As low as 10USDT", "账户余额年化收益n": "Account balance annualized income <span style='font-size:0.9rem;font-weight:bold;color:#EA3131;'>{0}</span>",
        "按天计息，按月支付，随时提现": "Pay per day, pay monthly, withdraw at any time", "返利": "Rebate", "绑定收款账户": "Binding collection account",
        "新手教学home": "Beginner", "银行卡账户": "Bank card account", "EPay账户": "EPay Account", "账户类型": "account type",
        "邮箱地址": "email address", "添加": "Add", "您还没有信用资本": "You still have no credit capital", "马上充值信用资本": "Immediately deposit credit capital",
        "您还没有信用额度": "You don't have a credit line yet", "马上获取信用额度": "Get credit line right away", "信用额度": "credits",
        "{0}前需还款金额": "Repayment amount before {0}", "逾期天数": "Days Overdue", "n天": "{0}day{1}", "逾期费用": "Overdue fee",
        "借款数量": "Number of loans", "余额还款": "Balance repayment", "数字币还款": "Cryptocurrency repayment",
        "请输入借款数量": "Please enter the amount of the loan", "请输入还款数量": "Please enter the amount of repayment",
        "免息截止日": "Interest-free deadline", "提示": "prompt",
        "还款提示": "1. You will use the cryptocurrecy credit for free within 7 days. After 7 days, we will charge the interest according to the amount you borrowed.\n2. Please make sure that your account is fully funded. When your account funds are 0, in order to ensure the normal operation of the platform funds, the system will automatically deduct your cryptocurrency assets;\n3. The cryptocurrency credit is prohibited from being used for withdrawal;",
        "需支付": "Payable", "年化利息收入": "Annualized interest income", "可用额度": "Available credit", "已用额度": "Used quota",
        "借款提示": "1. You will use the Cryptocurrency credit for free within 7 days. After 7 days, we will charge the interest according to the amount you borrowed.\n2. Please make sure that your account is fully funded. When your account funds are 0, in order to ensure the normal operation of the platform funds, the system will automatically deduct your cryptocurrency assets;\n3. The cryptocurrency credit is prohibited from being used for withdrawal;",
        "日逾期利息": "Overdue interest", "渠道充值": "Channel deposit", "地址充值": "Address deposit",
        "充值注意事项_credit": "Precautions:\n1. Minimum deposit amount 50USDT\u2248{0}CNY;\n2. The deposit currency is the basis of the credit line;\n3. The value of the deposit currency changes as the market exchange rate changes;\n4. When the account balance is less than the total value of the currency, the platform will automatically deduct the currency in which you generated the credit.",
        "数据仍在加载中，请稍后再试": "The data is still loading, please try again later", "借款成功": "Successful loan", "成功还款": "Successful repayment",
        "数字币总值": "Total value of Cryptocurrencys", "系统强制还款": "System mandatory repayment", "系统强制数字货币还款": "System mandatory crypto currency repayment",
        "信用滞纳金": "Credit late payment fee", "预计结算时间": "Estimated settlement time", "好友邀请收益": "Friend invites revenue",
        "请输入n位支付密码": "Please enter {0} digits to pay the password", "请输入n位验证码": "Please enter {0} digit verification code",
        "好友人数": "Number of friends", "年化收益率": "Annualized rate of return", "邀请收益余额": "Invited earnings balance",
        "借用信用金额": "Borrowing credit amount", "平仓委托成交": "Closing the entrusted transaction", "收益转入": "Transfer of income",
        "交易规则": "Trading Rules", "手续费返佣收益": "Commission fee rebate income", "手续费总额": "Total transaction fee", "返佣比率": "Rebate ratio",
        "借款转入": "Transfer of money", "滞纳金": "Late payment", "我要借款": "I want to borrow", "详情": "Details", "余额利息": "Balance interest",
        "保证金利息": "Margin interest", "信用资本利息": "Credit account interest", "结算时间": "Settlement time", "充值数字币": "deposit crypto currency",
        "实际到账": "Actual arrival", "一键还款": "One-click repayment", "还款数量": "Repayment amount", "余额不足": "Insufficient balance",
        "还款明细": "Repayment details", "借款明细": "Borrowing details", "冻结资产": "Frozen assets", "信用资本利息收益": "Credit account interest income",
        "交易ID": "Transaction ID", "借款日期": "Date of loan", "还款日期": "Repayment date", "借款天数": "Number of borrowing days",
        "日逾期利率": "Overdue interest rate", "余额宝账户": "YuEBao account", "信用资本明细": "Credit account details",
        "信用资本收益": "Credit capital gains", "类型": "Types of", "币币": "Coin to coin", "法币": "fiat currency", "提取信用资本": "Extract credit capital",
        "抵消信用资本": "Offset credit capital", "扣款数量": "Deduction amount", "信用资本余额": "Credit capital balance",
        "有新的版本,是否下载并安装": "Is there a new version, is it downloaded and installed?", "正在下载应用": "Downloading app",
        "其他金额": "other amounts", "支持": "Support", "单价": "Price", "限额": "Limit", "单笔": "Single payment",
        "可提数量": "Available amount", "提现数量": "Cash withdrawal amount", "提现手续费": "Cash withdrawal fee",
        "密码连续录入错误5次，12小时内禁止提现！": "The password is entered incorrectly 5 times, the withdrawal is prohibited within 12 hours!",
        "提现注意事项": "1. withdrawal fee: 5 USDT / time\n2. In order to protect the security of the fund account, when your account security policy is changed, the password is modified, and the new address is used to withdraw the currency, you must verify that the coin address is correct. Once you make a mistake, you will not be able to return.\n3. The loss caused by mistakes in the operation of personal input addresses and information is borne by the individual. ",
        "发现新版本,即将进行安装": "Find a new version, it will be downloaded and installed.",
        "买多": "Buy",
        "卖空": "Sell",
        "下单价": "Order price",
        "今日快讯": "News",
        "日期Format": "MM/dd/yyyy",
        "星期一": "Monday",
        "星期二": "Tuesday",
        "星期三": "Wednesday",
        "星期四": "Thursday",
        "星期五": "Friday",
        "星期六": "Saturday",
        "星期日": "Sunday",
        "余额宝明细": "YuEBao Details",
        "止盈价": "Stop Profit Target", "止损价": "Stop Loss",
        "收起": "Collapse",
        "追加保证金提示": "Tips\uFF1A\n1.Up to <b>{0}</b> USDT more\n2.The price after addition is\uFF1A<b>{1}</b> USDT",
        "减少保证金提示": "Tips\uFF1A\n1.Up to <b>{0}</b> USDT reduction\n2.The price after reduction is\uFF1A<b>{1}</b> USDT",
        "追加保证金": "Additional margin",
        "减少保证金": "Reduction of margin",
        "限价平仓": "Stop Profit/Loss",
        "市价平仓": "Close position",
        "输入追加金额": "Enter additional margin",
        "输入减少金额": "Enter reduction of margin",
        "强平价格": "Close price",
        "没有可用的信用资本可以提现": "There is no available credit amount to withdraw",
        "马上分享": "Share now",
        "用途": "Purpose",
        "您的信用额度已被全部取用，需还款后可再度借用哦！": "Your credit line has been fully used. You can borrow it again after repayment.",
        "名称": "Name",
        "提现相关": "Withdraw",
        "充值相关": "Deposit",
        "平台相关": "Platform",
        "账户相关": "Account",
        "分享": "Share",
        "查看大图": "Big landscape",
        "持仓列表": "Positions",
        "确定要跳转到实盘模式吗？": "Are you sure you want to get into the real world?",
        "K线图设置": "K line setting",
        "卖价K线图": "bid price",
        "买价K线图": "offer price",
        "默认": "default",
        "在线客服": "Online Service",
        "提现渠道": "Channel",
        "充值返回提示": "For the sake of your capital security, please click on the page \"I have completed payment\" to complete payment, and click \"Cancel order\" to cancel the order.",
        "安全中心": "Security Center",
        "止盈金额": "Stop Profit Amount",
        "止损金额": "Stop Loss Amount",
        "盯盘助手": "Staring Assistant",
        "提现注意事项_法币": "* The minimum cash withdrawal amount is {1}USDT.\n* The maximum single cash withdrawal amount is 7000 USDT.\n*Withdrawal fee {0}USDT/pen",
        "提现注意事项_币币": "*The minimum cash withdrawal amount is {1}{2}.\n* The maximum single cash withdrawal amount is {3} USDT.\n*Withdrawal fee {0}USDT/pen",
        "USDT重要提示": "Precautions\n1.Minimum deposit amount: {1}, the deposit value less than {1} will not be credited and cannot be returned.\n2.Please do not transfer any non-USDT assets to the above address, otherwise it will not be recovered.\n3.The completion time of the blockchain node is about 10-60 minutes , please be patient, if you have any questions, please contact online customer service. ",
        "K线图颜色": "K line drawing color",
        "红涨绿跌": "Red and green falls",
        "绿涨红跌": "Green is rising red",
        "帮助": "Help",
        "安卓系统太低": "Your Android system is: {0}, please upgrade your mobile operating system",
        "宣传语": "Do not issue currency, do not use currency, do not raise funds, only serve mainstream digital assets",
        "不发币": "Do not issue currency, do not use currency, do not raise funds",
        "只服务主流数字资产": "only serve <span style='font-weight:bold;color:#EA3131;'>mainstream</span> digital assets",
        "订单撮合中": "Your order is being matched, please wait...",
        "正在平仓": "Closing",
        "正在撤单": "Canceling",
        "平仓成功": "Close order sucessfully",
        "网络异常，请检查您的网络连接": "Network error,please check your network connection",
        "你还是未成年人": "You are still a minor, go back and study hard, and look forward to seeing you come back as an adult!",
        "绑定银行卡提示": "Dear users, Hello:\nAt present, our platform only supports the binding of \u00A0bank cards in mainland China, and we apologize for any inconvenience.\nAt the same time, in order to ensure the security of account funds, please carefully and correctly fill in your receiving account information.\nThe platform will not be responsible for any loss of funds caused by incorrect account information.",
    };
    return lang_en_US;
}());
export { lang_en_US };
//# sourceMappingURL=lang_en_US.js.map